Clang-tidy config + major mechanical refactor

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -10,6 +10,9 @@ on:
 permissions:
   contents: read
 
+env:
+  clang-version: 21
+
 jobs:
   font-dejavusans:
     name: DejaVuSans font
@@ -85,6 +88,38 @@ jobs:
           EOL
 
           pio run -e esp32dev
+
+      - name: PlatformIO compilation database
+        run: pio run -e esp32dev -t compiledb
+
+      - name: Clang
+        uses: cpp-linter/cpp-linter-action@b6edc0625e3941baa1797f4b4326adeab6890c97 # v2.16.7
+        id: clang
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          version: ${{ env.clang-version }}
+          files-changed-only: false
+          format-review: true
+          ignore: "*|!firmware/src/fonts/DejaVuSansFont.cpp|!firmware/include/fonts/DejaVuSansFont.h"
+          passive-reviews: true
+          step-summary: true
+          style: file
+          tidy-checks: ""
+          tidy-review: true
+
+      - name: Clang summary
+        env:
+          clang-threshold: 3
+        run: |
+          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
+          echo "Clang report:"
+          if [ -n "${{ github.event.pull_request.number }}" ]; then
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
+          else
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          fi
+          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))
 
   mode-dynamic:
     name: Dynamic mode
@@ -191,6 +226,38 @@ jobs:
 
           pio run -e esp32dev
 
+      - name: PlatformIO compilation database
+        run: pio run -e esp32dev -t compiledb
+
+      - name: Clang
+        uses: cpp-linter/cpp-linter-action@b6edc0625e3941baa1797f4b4326adeab6890c97 # v2.16.7
+        id: clang
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          version: ${{ env.clang-version }}
+          files-changed-only: false
+          format-review: true
+          ignore: "*|!firmware/src/modes/DynamicMode.cpp|!firmware/include/modes/DynamicMode.h"
+          passive-reviews: true
+          step-summary: true
+          style: file
+          tidy-checks: ""
+          tidy-review: true
+
+      - name: Clang summary
+        env:
+          clang-threshold: 0
+        run: |
+          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
+          echo "Clang report:"
+          if [ -n "${{ github.event.pull_request.number }}" ]; then
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
+          else
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          fi
+          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))
+
   mode-static:
     name: Static mode
     runs-on: ubuntu-latest
@@ -279,3 +346,35 @@ jobs:
           EOL
 
           pio run -e esp32dev
+
+      - name: PlatformIO compilation database
+        run: pio run -e esp32dev -t compiledb
+
+      - name: Clang
+        uses: cpp-linter/cpp-linter-action@b6edc0625e3941baa1797f4b4326adeab6890c97 # v2.16.7
+        id: clang
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          version: ${{ env.clang-version }}
+          files-changed-only: false
+          format-review: true
+          ignore: "*|!firmware/src/modes/StaticMode.cpp|!firmware/include/modes/StaticMode.h"
+          passive-reviews: true
+          step-summary: true
+          style: file
+          tidy-checks: ""
+          tidy-review: true
+
+      - name: Clang summary
+        env:
+          clang-threshold: 0
+        run: |
+          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
+          echo "Clang report:"
+          if [ -n "${{ github.event.pull_request.number }}" ]; then
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
+          else
+            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          fi
+          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))
