Refactored workflows and templates (#250)
* Refactored workflows

* Pin actions to commits, pin platformio version

* Node.js 24 and updated templates

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -24,11 +24,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install tools/
 
@@ -70,10 +70,10 @@ jobs:
 
       - run: python -m frekvens.AnimationSplitter --input Animation.csv
 
-      - uses: andstor/file-existence-action@v3
+      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
         with:
           fail: true
-          files: "Animation-1.csv, Animation-2.csv"
+          files: Animation-1.csv, Animation-2.csv
 
   art-net-streamer:
     name: Art-Net streamer
@@ -81,11 +81,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install tools/
 
@@ -174,11 +174,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install tools/
 
@@ -268,11 +268,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install tools/
 
@@ -361,31 +361,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install -r extra/Python/requirements.txt
 
       - run: python extra/Python/FontGenerator.py --input DejaVuSans --size 8
 
-      - uses: andstor/file-existence-action@v3
+      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
         with:
           fail: true
-          files: "DejaVuSansFont.cpp, DejaVuSansFont.h"
+          files: DejaVuSansFont.cpp, DejaVuSansFont.h
 
   home-thermometer-demo:
     name: Home thermometer demo
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: pip install tools/
 
@@ -406,11 +406,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
 
       - run: |
           cat <<EOL > Animation.csv
@@ -450,10 +450,10 @@ jobs:
 
       - run: python extra/Python/ModeGenerator.py --input Animation.csv
 
-      - uses: andstor/file-existence-action@v3
+      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
         with:
           fail: true
-          files: "AnimationMode.cpp, AnimationMode.h"
+          files: AnimationMode.cpp, AnimationMode.h
 
       - run: |
           cat <<EOL > Drawing.csv
@@ -477,7 +477,69 @@ jobs:
 
       - run: python extra/Python/ModeGenerator.py --input Drawing.csv
 
-      - uses: andstor/file-existence-action@v3
+      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
         with:
           fail: true
-          files: "DrawingMode.cpp, DrawingMode.h"
+          files: DrawingMode.cpp, DrawingMode.h
+
+  x509_crt_bundle:
+    name: x509 certificate bundle
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+        with:
+          python-version: 3.13
+
+      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+
+      - run: pip install -r .github/platformio/requirements.txt
+
+      - run: |
+          cat <<EOL > .env
+          HOSTNAME='frekvens'
+          IKEA_FREKVENS='true'
+          MODE_GOOGLEWEATHER='true'
+          MODE_OPENMETEO='true'
+          MODE_OPENWEATHER='true'
+          MODE_WTTRIN='true'
+          MODE_YR='true'
+          NAME='Frekvens'
+          EOL
+
+      - run: |
+          cat <<EOL > firmware/include/config/secrets.h
+          #pragma once
+          #define GOOGLEWEATHER_KEY "redacted"
+          #define LATITUDE "0.000"
+          #define LONGITUDE "0.000"
+          #define OPENWEATHER_KEY "redacted"
+          #define PIN_CS 1
+          #define PIN_MOSI 2
+          #define PIN_OE 3
+          #define PIN_SCLK 4
+          #define WIFI_KEY "redacted"
+          #define WIFI_SSID "redacted"
+          EOL
+
+      - run: pio run --environment esp32dev
+        continue-on-error: true
+
+      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
+        with:
+          fail: true
+          files: firmware/certs/bundle/ca_roots.pem, firmware/embed/x509_crt_bundle.bin
+
+      - run: |
+          git clone --branch release/v5.5 --filter=blob:none --sparse https://github.com/espressif/esp-idf.git
+          cd esp-idf
+          git sparse-checkout add components/mbedtls/esp_crt_bundle
+
+      - run: |
+          python esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input firmware/certs/bundle
+          if cmp x509_crt_bundle firmware/embed/x509_crt_bundle.bin; then
+            echo "Root CA bundles identical."
+            exit 0
+          fi
+          echo "Unexpected error or file mismatch."
+          exit 1
